import Head from 'next/head'
import Image from 'next/image'
import { useRef,useState,useEffect } from 'react'
import styles from '../styles/Home.module.css'

const HEIGHT = 743
const WIDTH = 309
const BLOCK_COLORS=["#327AB8","#3AD9A7","#FFC247","#9951B3","#CD4C4C"];
const BACKGROUND="#4F5165"
let context;
const getNeighbours = (tiles) => {
  return Array(tiles.reduce((a,b)=>Math.max(a,b),0)).fill(0).map((_,id)=>{
    id++
    let neighbours=[]
    tiles.forEach((tileID,index)=>{
      if(tileID==id){
        for(let i = -1;i<2;i++){
          for(let j =-1;j<2;j++){
            if(0<=index%10+i<10&&0<=Math.floor(index/10)+j<20&&tiles[index+i+10*j]!=tileID){
              neighbours.push(tiles[index+i+10*j])
            }
          }
        }
      }
    })
    return neighbours
  })
}
export default function Home() {
  const ref = useRef();
  const [state,setState] = useState(0);
  useEffect(()=>{
    
    context=ref.current.getContext("2d");
  },[])
  useEffect(()=>{
    let tiles=state[1];
    let colors=["#fff"];
    getNeighbours(tiles).forEach((neighbours,id)=>{
      id++;
      neighbours=neighbours.filter(x=>x<id)
      colors.push(BLOCK_COLORS.filter((x)=>neighbours.reduce((a,b)=>a==colors[b]?0:a,x)!=0)[0])
    })
    tiles.forEach((id,i) => {
      context.fillStyle=colors[id];
      context.fillRect(30*i%10+i,30*Math.floor(i/10)+i,30,30)  
    });
  },[state]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Tetris</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <div className="canvas">
          <div className="playground-container">
            <canvas height={HEIGHT} width={WIDTH} ref={ref}/>
          </div>
          <div className="information-block">
            <div className="nextElement-block" >

            </div>
            <div className="info-block">
              <button className="start-btn">Start</button>
              <button className="restart-btn">Restart</button>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
