import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import styles from '../styles/Home.module.css'

const HEIGHT = 720
const WIDTH = 300

export default function Home() {
  let ref = useRef();



  return (
    <div className={styles.container}>
      <Head>
        <title>Tetris</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <div className="canvas">
          <div className="playground-container">
            <canvas height={HEIGHT} width={WIDTH} ref={ref}/>
          </div>
          <div className="information-block">
            <div className="nextElement-block">

            </div>
            <div className="info-block">
              <button className="start-btn">Start</button>
              <button className="restart-btn">Restart</button>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
